pipeline {
  agent any

  environment {
    AWS_REGION   = "ap-southeast-2"
    AWS_ACCOUNT  = "421869852482"
    ECR_REPO     = "week3-app"
    ECR_REGISTRY = "${AWS_ACCOUNT}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    IMAGE_TAG    = "${BUILD_NUMBER}"

    GITOPS_DIR   = "week3-gitops"
    VALUES_FILE  = "envs/dev/values.yaml"
  }

  stages {
    stage("Checkout") {
      steps { checkout scm }
    }

    stage("Build image") {
      steps {
        dir("week3") {
          sh """
            docker build -t ${ECR_REPO}:${IMAGE_TAG} -f dockerfile .
            docker tag ${ECR_REPO}:${IMAGE_TAG} ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}
          """
        }
      }
    }

    stage("Push to ECR") {
      steps {
        withCredentials([usernamePassword(credentialsId: 'aws-creds', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          sh """
            aws sts get-caller-identity
            aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
            docker push ${ECR_REGISTRY}/${ECR_REPO}:${IMAGE_TAG}
          """
        }
      }
    }

    stage("Update GitOps repo") {
      steps {
        withCredentials([string(credentialsId: 'github-pat', variable: 'GITHUB_TOKEN')]) {
          sh """
            rm -rf ${GITOPS_DIR}
            git clone https://${GITHUB_TOKEN}@github.com/techngi/week3-gitops.git ${GITOPS_DIR}
            cd ${GITOPS_DIR}

            # preserve indentation, replace tag value
            sed -i -E 's|(tag:\\s*).*|\\1"${IMAGE_TAG}"|' ${VALUES_FILE}

            git config user.name "jenkins"
            git config user.email "jenkins@local"
            git add ${VALUES_FILE}
            git commit -m "Deploy ${ECR_REPO}:${IMAGE_TAG} to dev" || echo "No changes to commit"
            git push
          """
        }
      }
    }
  }
}
