// Jenkinsfile for Week 3 – Flask app + Docker
def dockerImage

pipeline {
    agent any

    environment {
        IMAGE_NAME     = "sanaqvi573/week3-app"   // your Docker Hub repo
        DOCKERHUB_CRED = "dockerhub-creds"        // Jenkins DockerHub credential ID
    }

    stages {
        stage('Checkout') {
            steps {
                // pulls code from Github
                checkout scm
            }
        }

        stage('Build Docker image') {
            steps {
                // build from week3 directory, using dockerfile file
                dir('week3') {
                    script {
                        dockerImage = docker.build(
                            "${IMAGE_NAME}:${env.BUILD_NUMBER}",
                            "-f dockerfile ."
                        )
                    }
                }
            }
        }

        stage('Push image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', DOCKERHUB_CRED) {
                        dockerImage.push("${env.BUILD_NUMBER}")
                        dockerImage.push("latest")
                    }
                }
            }
        }
        stage('Deploy to Lab VM') {
            steps {
                sshagent(credentials: ['jenkins-ssh-key']) {
                    sh '''
                    ssh -o StrictHostKeyChecking=no vagrant@192.168.56.11 '
                        docker pull sanaqvi573/week3-app:latest &&
                        docker stop week3-app || true &&
                        docker rm week3-app || true &&
                        docker run -d --name week3-app -p 5000:5000 sanaqvi573/week3-app:latest
                    '
                    '''
                }
            }
        }


    }
}
